-- -*- mode: sql -*-
DROP TABLE IF EXISTS `TLS203_APPLN_ABSTR`;
CREATE TABLE IF NOT EXISTS `TLS203_APPLN_ABSTR` (
  appln_id int NOT NULL default 0,
  appln_abstract TEXT,
  PRIMARY KEY  (appln_id)
)  
MAX_ROWS = 40000000
AVG_ROW_LENGTH=800
ENGINE = MyISAM
CHARACTER SET utf8 COLLATE utf8_unicode_ci;

